export const sentimentColors: Record<string, string> = {
  admiration: "bg-emerald-100 border-emerald-300",
  amusement: "bg-yellow-100 border-yellow-300",
  anger: "bg-red-100 border-red-300",
  annoyance: "bg-orange-100 border-orange-300",
  approval: "bg-green-100 border-green-300",
  caring: "bg-pink-100 border-pink-300",
  confusion: "bg-purple-100 border-purple-300",
  curiosity: "bg-indigo-100 border-indigo-300",
  desire: "bg-fuchsia-100 border-fuchsia-300",
  disappointment: "bg-blue-200 border-blue-400",
  disapproval: "bg-red-200 border-red-400",
  disgust: "bg-emerald-200 border-emerald-400",
  embarrassment: "bg-rose-100 border-rose-300",
  excitement: "bg-amber-100 border-amber-300",
  fear: "bg-purple-100 border-purple-300",
  gratitude: "bg-teal-100 border-teal-300",
  grief: "bg-slate-200 border-slate-400",
  joy: "bg-yellow-100 border-yellow-300",
  love: "bg-pink-100 border-pink-300",
  nervousness: "bg-violet-100 border-violet-300",
  optimism: "bg-cyan-100 border-cyan-300",
  pride: "bg-indigo-100 border-indigo-300",
  realization: "bg-sky-100 border-sky-300",
  relief: "bg-teal-50 border-teal-200",
  remorse: "bg-zinc-100 border-zinc-300",
  sadness: "bg-blue-100 border-blue-300",
  surprise: "bg-orange-100 border-orange-300",
  neutral: "bg-gray-100 border-gray-300",
};

export const sentimentTextColors: Record<string, string> = {
  admiration: "text-emerald-800",
  amusement: "text-yellow-800",
  anger: "text-red-800",
  annoyance: "text-orange-800",
  approval: "text-green-800",
  caring: "text-pink-800",
  confusion: "text-purple-800",
  curiosity: "text-indigo-800",
  desire: "text-fuchsia-800",
  disappointment: "text-blue-800",
  disapproval: "text-red-900",
  disgust: "text-emerald-900",
  embarrassment: "text-rose-800",
  excitement: "text-amber-800",
  fear: "text-purple-800",
  gratitude: "text-teal-800",
  grief: "text-slate-800",
  joy: "text-yellow-800",
  love: "text-pink-800",
  nervousness: "text-violet-800",
  optimism: "text-cyan-800",
  pride: "text-indigo-800",
  realization: "text-sky-800",
  relief: "text-teal-900",
  remorse: "text-zinc-800",
  sadness: "text-blue-800",
  surprise: "text-orange-800",
  neutral: "text-gray-800",
};

// List of all supported sentiments
export const sentimentList = [
  "admiration",
  "amusement",
  "anger",
  "annoyance",
  "approval",
  "caring",
  "confusion",
  "curiosity",
  "desire",
  "disappointment",
  "disapproval",
  "disgust",
  "embarrassment",
  "excitement",
  "fear",
  "gratitude",
  "grief",
  "joy",
  "love",
  "nervousness",
  "optimism",
  "pride",
  "realization",
  "relief",
  "remorse",
  "sadness",
  "surprise",
  "neutral",
];
